version: "3.8"
services:
  mysql:
    image: mysql:latest  # Docker Hub의 MySQL 이미지
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"  # 로컬 3306 -> 컨테이너 3306
    volumes:
      - ./mysql-data:/var/lib/mysql  # 데이터 영구 저장